EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes

VIA_ENABLE = yes
VIAL_ENABLE = yes

VIAL_INSECURE = yes

LTO_ENABLE = yes
COMMAND_ENABLE = yes
MIDI_ENABLE = yes
NKRO_ENABLE = no
CONSOLE_ENABLE = no
QMK_SETTINGS = no
KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE = yes
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no
STENO_ENABLE = no