#pragma once

// Define DPIs 
#define PLOOPY_DPI_OPTIONS { 800, 1200, 1600, 2400 }
#define PLOOPY_DPI_DEFAULT 2
#define PLOOPY_DRAGSCROLL_FIXED 1
#define PLOOPY_DRAGSCROLL_INVERT 0
#define PLOOPY_DRAGSCROLL_DPI 100
#define PLOOPY_DRAGSCROLL_DENOMINATOR 180 // Number for drag scroll accumulator

#define DYNAMIC_KEYMAP_LAYER_COUNT 5