VIA_ENABLE = yes
VIAL_ENABLE = yes
# VIAL_INSECURE = yes
MIDI_ENABLE = yes
MOUSEKEY_ENABLE = yes
DYNAMIC_KEYMAP_ENABLE = yes
TAP_DANCE_ENABLE = yes
# LEADER_ENABLE = yes

# Flags to save space
LTO_ENABLE = yes
QMK_SETTINGS = no
KEY_OVERRIDE_ENABLE = no
COMBO_ENABLE = no
EXTRAKEY_ENABLE = no

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
MUSIC_ENABLE = no
