VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
# MIDI_ENABLE = yes
MOUSEKEY_ENABLE = yes
DYNAMIC_KEYMAP_ENABLE = yes
TAP_DANCE_ENABLE = yes
# LEADER_ENABLE = yes

# Disable these to save space
LTO_ENABLE = yes
QMK_SETTINGS = no
KEY_OVERRIDE_ENABLE = no