VIA_ENABLE = yes
LTO_ENABLE = yes
VIAL_ENABLE = yes
ENCODER_MAP_ENABLE = yes
MOUSEKEY_ENABLE = yes
COMBOS_ENABLE = no

CONSOLE_ENABLE = no
QMK_SETTINGS = no
KEY_OVERRIDE_ENABLE = no
COMBO_ENABLE = no
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
MUSIC_ENABLE = no
COMMAND_ENABLE = no


# CONVERT_TO=promicro_rp2040
# BOOTLOADER = rp2040
# MIDI_ENABLE = yes
NKRO_ENABLE = no