VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes
ENCODER_MAP_ENABLE = yes
MIDI_ENABLE = yes
MOUSEKEY_ENABLE = yes
DYNAMIC_KEYMAP_ENABLE = yes
TAP_DANCE_ENABLE = yes
LEADER_ENABLE = yes
VIAL_INSECURE = yes

VPATH += keyboards/keychron/common
SRC += keychron_common.c
