EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes

VIA_ENABLE = yes
VIAL_ENABLE = yes

VIAL_INSECURE = yes

LTO_ENABLE = yes
COMMAND_ENABLE = yes
MIDI_ENABLE = yes
NKRO_ENABLE = yes
CONSOLE_ENABLE = yes
QMK_SETTINGS = no
KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE = yes
SPACE_CADET_ENABLE = yes
MAGIC_ENABLE = yes
COMMAND_ENABLE = yes

AUDIO_ENABLE = yes

DEBOUNCE_TYPE = asym_eager_defer_pk

SRC += muse.c