OLED_ENABLE = yes
# OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
ENCODER_MAP_ENABLE = no
# RGBLIGHT_ENABLE = no
MOUSEKEY_ENABLE = yes


VIA_ENABLE = yes
VIAL_ENABLE = yes


# Flags to save space
LTO_ENABLE = yes
# CONSOLE_ENABLE = no
# QMK_SETTINGS = no
# KEY_OVERRIDE_ENABLE = no
# COMBO_ENABLE = no
# SPACE_CADET_ENABLE = no
# MAGIC_ENABLE = no
# AVR_USE_MINIMAL_PRINTF = yes
MUSIC_ENABLE = no
COMMAND_ENABLE = yes


CONVERT_TO=elite_pi
BOOTLOADER = rp2040
MIDI_ENABLE = yes
NKRO_ENABLE = no
# WPM_ENABLE = yes
CONSOLE_ENABLE = yes
QMK_SETTINGS = no
KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE = yes
SPACE_CADET_ENABLE = yes
MAGIC_ENABLE = yes
COMMAND_ENABLE = yes
RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
VIALRGB_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
CIRQUE_PINNACLE_DIAMETER_MM = 40
