OLED_ENABLE = yes
# OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
ENCODER_MAP_ENABLE = yes
RGBLIGHT_ENABLE = no
MOUSEKEY_ENABLE = yes


VIA_ENABLE = yes
VIAL_ENABLE = yes


# Flags to save space
LTO_ENABLE = yes
CONSOLE_ENABLE = no
QMK_SETTINGS = no
KEY_OVERRIDE_ENABLE = no
COMBO_ENABLE = no
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
MUSIC_ENABLE = no
# COMMAND_ENABLE = yes


# CONVERT_TO=promicro_rp2040
# BOOTLOADER = rp2040
# MIDI_ENABLE = yes
NKRO_ENABLE = no